on:
  workflow_dispatch:
    inputs:
      slack_invite_url:
        description: "Slack invite URL"
        required: true
        type: string

jobs:
  update-token:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      # Mask the invite URL so it doesn't get printed in the logs.
      # This adds a layer of protection in case we run the workflow with
      # a private invite URL by mistake.
      - run: |
          url=$(jq -r '.inputs.slack_invite_url' $GITHUB_EVENT_PATH)
          echo "::add-mask::$url"
          echo SLACK_INVITE_URL="$url" >> $GITHUB_ENV

      - run: >
          echo $SLACK_INVITE_URL 
          | grep -E 'https://join\.slack\.com/t/developersitalia/shared_invite/zt-[A-Za-z0-9-]+' > /dev/null 
          || (echo "::error::Input invite URL doesn't look like an invite to Developers Italia's Slack"; exit 1)

      - run: |
          sed "s@SLACK_INVITE_URL@$SLACK_INVITE_URL@g" < index.tpl > index.html

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update Slack token"
