on:
  workflow_dispatch:
    inputs:
      token:
        description: "Slack invite URL"
        required: true
        type: string

jobs:
  update-token:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - run: |
          cat << EOF > index.html
          <!DOCTYPE html>

          <html>
            <head>
              <meta charset="utf-8">
              <title>Redirect a Slack Developers Italia</title>
              <meta http-equiv="refresh" content="0; URL=$INVITE_URL">
            </head>
          </html>
          EOF
        env:
          INVITE_URL: ${{ inputs.token }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update Slack token"
